---
- name: Load OS-specific defaults
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "default.yml"
      paths:
        - "{{ role_path }}/vars"


- name: Determine effective CDB manager packages
  set_fact:
    _cdb_manager_packages: "{{ cdb_manager_packages_override | default(cdb_manager_packages) }}"
